version: 2
jobs:
  lint:
    docker:
    - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
    - checkout
    - run: yarn install
    - run: yarn lint

workflows:
  version: 2
  myworkflow:
    jobs:
    - lint